apiVersion: v1
kind: Service
metadata:
  name: {{ include "tugboat.fullname" . }}-notifier-slack
  labels:
    {{- include "tugboat.labels" . | nindent 4 }}
    {{- include "tugboat-notifier-slack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tugboatNotifierSlack.service.type }}
  ports:
    - port: {{ .Values.tugboatNotifierSlack.service.externalPort }}
      targetPort: {{ .Values.tugboatNotifierSlack.service.internalPort }}
      protocol: TCP
      name: http
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: grpc
  selector:
    {{- include "tugboat.selectorLabels" . | nindent 4 }}
    {{- include "tugboat-notifier-slack.selectorLabels" . | nindent 4 }}
