apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "tugboat.engineering:launch:reader"
rules:
  - apiGroups: ["tugboat.engineering"]
    resources: ["launches"]
    verbs: ["get", "list", "watch"]