apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tugboat-controller.fullname" . }}-config
  labels:
    app: {{ template "tugboat-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  repos.yaml: |
    chartRepositories:
{{- range .Values.chartRepositories }}
      - name: {{ required "name required" .name }}
        url: {{ required "url required" .url }}
        caFile: {{ .caFile }}
        certFile: {{ .certFile }}
        keyFile: {{ .keyFile }}
        password: {{ .password }}
        username: {{ .username }}  
{{- end }}
