apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tugboat-controller.fullname" . }}
  labels:
    app: {{ template "tugboat-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- include "tugboat-controller.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "tugboat-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "tugboat-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tugboat-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ template "tugboat-controller.name" . }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/usr/local/bin/tugboat-controller']
          args: ['configure', '--verbose']
          volumeMounts:
            - name: helm-cache-volume
              mountPath: /home/appuser/.cache/helm
            - name: helm-config-volume
              mountPath: /home/appuser/.config/helm
      containers:
        - name: {{ template "tugboat-controller.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Never
          env:
            - name: TMPDIR
              value: "/home/appuser/tmp"
            - name: TUGBOAT_HTTP_PORT
              value: "{{ .Values.service.internalPort }}"
            - name: TUGBOAT_HTTPS_CERT_FILE
              value: "/etc/https-secrets/server-cert.pem"
            - name: TUGBOAT_HTTPS_KEY_FILE
              value: "/etc/https-secrets/server-key.pem"
            - name: TUGBOAT_HTTPS_PORT
              value: "3443"
            {{- range $k, $v := .Values.image.env }}
            - name: $k
              value: "$v"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.service.internalPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: https-secrets
              mountPath: "/etc/https-secrets"
              readOnly: true
            - name: helm-cache-volume
              mountPath: /home/appuser/.cache/helm
            - name: helm-config-volume
              mountPath: /home/appuser/.config/helm
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: https-secrets
          secret:
            secretName: {{ include "tugboat-controller.fullname" . }}
            defaultMode: 0444
            items:
              - key: serverCert
                path: "server-cert.pem"
              - key: serverKey
                path: "server-key.pem"
        - name: {{ template "tugboat-controller.fullname" . }}-config-volume
          configMap:
            name: {{ template "tugboat-controller.fullname" . }}-config
        - name: helm-cache-volume
        - name: helm-config-volume