apiVersion: v1
kind: Service
metadata:
  name: {{ include "tugboat.fullname" . }}-slack
  labels:
    {{- include "tugboat.labels" . | nindent 4 }}
    {{- include "tugboat-slack.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.tugboatSlack.service.type }}
  ports:
    - port: {{ .Values.tugboatSlack.service.externalPort }}
      targetPort: {{ .Values.tugboatSlack.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "tugboat.selectorLabels" . | nindent 4 }}
    {{- include "tugboat-slack.selectorLabels" . | nindent 4 }}
