/*
LICENSE
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	engineeringtugboatv1alpha1 "github.com/object88/tugboat/apps/tugboat-controller/pkg/apis/engineering.tugboat/v1alpha1"
	versioned "github.com/object88/tugboat/apps/tugboat-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/object88/tugboat/apps/tugboat-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/object88/tugboat/apps/tugboat-controller/pkg/client/listers/engineering.tugboat/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ReleaseHistoryInformer provides access to a shared informer and lister for
// ReleaseHistories.
type ReleaseHistoryInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ReleaseHistoryLister
}

type releaseHistoryInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewReleaseHistoryInformer constructs a new informer for ReleaseHistory type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewReleaseHistoryInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredReleaseHistoryInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredReleaseHistoryInformer constructs a new informer for ReleaseHistory type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredReleaseHistoryInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TugboatV1alpha1().ReleaseHistories(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TugboatV1alpha1().ReleaseHistories(namespace).Watch(context.TODO(), options)
			},
		},
		&engineeringtugboatv1alpha1.ReleaseHistory{},
		resyncPeriod,
		indexers,
	)
}

func (f *releaseHistoryInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredReleaseHistoryInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *releaseHistoryInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&engineeringtugboatv1alpha1.ReleaseHistory{}, f.defaultInformer)
}

func (f *releaseHistoryInformer) Lister() v1alpha1.ReleaseHistoryLister {
	return v1alpha1.NewReleaseHistoryLister(f.Informer().GetIndexer())
}
