apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: launches.tugboat.engineering
spec:
  group: tugboat.engineering
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                chart:
                  type: string
                version:
                  type: string
                  # This pattern is copied directly from:
                  # https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
                  pattern: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
                encoding:
                  type: string
  scope: Namespaced
  names:
    kind: Launch
    plural: launches
    singular: launch
    shortNames:
      - lte
