apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repositories.tugboat.engineering
spec:
  group: tugboat.engineering
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
                chartCacheLimit:
                  type: integer
      additionalPrinterColumns:
        - name: name
          type: string
          jsonPath: .spec.name
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    kind: Repository
    plural: repositories
    singular: repository
    shortNames:
      - rte
