/*
LICENSE
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// LaunchListerExpansion allows custom methods to be added to
// LaunchLister.
type LaunchListerExpansion interface{}

// LaunchNamespaceListerExpansion allows custom methods to be added to
// LaunchNamespaceLister.
type LaunchNamespaceListerExpansion interface{}

// RepositoryListerExpansion allows custom methods to be added to
// RepositoryLister.
type RepositoryListerExpansion interface{}

// RepositoryNamespaceListerExpansion allows custom methods to be added to
// RepositoryNamespaceLister.
type RepositoryNamespaceListerExpansion interface{}
