apiVersion: v1
kind: Service
metadata:
  name: {{ include "tugboat-watcher.fullname" . }}
  labels:
    {{- include "tugboat-watcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "tugboat-watcher.selectorLabels" . | nindent 4 }}
