apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "tugboat.engineering:releasehistories:cdreader-read"
  labels:
    {{- include "tugboat.labels" . | nindent 4 }}
    {{- include "tugboat-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "tugboat.engineering:releasehistories:reader"
subjects:
  - kind: ServiceAccount
    name: {{ include "tugboat-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}