apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "tugboat.engineering:releasehistories:reader"
  labels:
    {{- include "tugboat.labels" . | nindent 4 }}
    {{- include "tugboat-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: ["tugboat.engineering"]
    resources: ["releasehistories"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
