apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "tugboat.fullname" . }}-controller-customresource-mutate
  labels:
    {{- include "tugboat.labels" . | nindent 4 }}
    {{- include "tugboat-controller.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "tugboat.fullname" . }}-controller-customresource-mutate.tugboat.engineering
    matchPolicy: Equivalent
    clientConfig:
      service:
        name: {{ include "tugboat.fullname" . }}-controller
        namespace: {{ .Release.Namespace }}
        path: /v1/api/mutate
      caBundle: {{ .Values.network.caBundle }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["*"]
        resources: ["*"]
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        - key: engineering.tugboat.namespace
          operator: NotIn
          values:
            - no-watch
      # matchLabels:
      #   engineering.tugboat: watch
    failurePolicy: Fail
    sideEffects: "None"
    admissionReviewVersions: ["v1"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "tugboat.fullname" . }}-controller-customresource-validate
  labels:
    {{- include "tugboat.labels" . | nindent 4 }}
    {{- include "tugboat-controller.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "tugboat.fullname" . }}-controller-customresource-validate.tugboat.engineering
    clientConfig:
      service:
        name: {{ include "tugboat.fullname" . }}-controller
        namespace: {{ .Release.Namespace }}
        path: /v1/api/validate
      caBundle: {{ .Values.network.caBundle }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["tugboat.engineering"]
        apiVersions: ["v1alpha1"]
        resources: ["releasehistories"]
    failurePolicy: Fail
    sideEffects: "None"
    admissionReviewVersions: ["v1"]
