{{- if not .Values.tugboatController.tls.secretName }}
{{ $ca := genCA "svc-cat-ca" 3650 }}
{{ $cn := printf "%s-controller.%s.svc" (include "tugboat.fullname" .) .Release.Namespace }}
{{ $server := genSignedCert $cn nil (list $cn) 365 $ca }}
{{ $client := genSignedCert "" nil nil 365 $ca }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tugboat.fullname" . }}-controller
  labels:
    {{- include "tugboat.labels" . | nindent 4 }}
data:
  caCert: {{ b64enc $ca.Cert }}
  clientCert: {{ b64enc $client.Key }}
  clientKey: {{ b64enc $client.Cert }}
  serverCert: {{ b64enc $server.Cert }}
  serverKey: {{ b64enc $server.Key }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "tugboat.fullname" . }}-controller-customresource-mutate
  labels:
    {{- include "tugboat.labels" . | nindent 4 }}
    {{- include "tugboat-controller.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "tugboat.fullname" . }}-controller-customresource-mutate.tugboat.engineering
    matchPolicy: Equivalent
    clientConfig:
      service:
        name: {{ include "tugboat.fullname" . }}-controller
        namespace: {{ .Release.Namespace }}
        path: /v1/api/mutate
      caBundle: {{ b64enc $ca.Cert }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["*"]
        resources: ["*"]
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        - key: engineering.tugboat.namespace
          operator: NotIn
          values:
            - no-watch
      # matchLabels:
      #   engineering.tugboat: watch
    failurePolicy: Fail
    sideEffects: "None"
    admissionReviewVersions: ["v1"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "tugboat.fullname" . }}-controller-customresource-validate
  labels:
    {{- include "tugboat.labels" . | nindent 4 }}
    {{- include "tugboat-controller.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "tugboat.fullname" . }}-controller-customresource-validate.tugboat.engineering
    clientConfig:
      service:
        name: {{ include "tugboat.fullname" . }}-controller
        namespace: {{ .Release.Namespace }}
        path: /v1/api/validate
      caBundle: {{ b64enc $ca.Cert }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["tugboat.engineering"]
        apiVersions: ["v1alpha1"]
        resources: ["releasehistories"]
    failurePolicy: Fail
    sideEffects: "None"
    admissionReviewVersions: ["v1"]
{{ end }}
