apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: releasehistories.tugboat.engineering
  labels:
    {{- include "tugboat.labels" . | nindent 4 }}
    {{- include "tugboat-controller.labels" . | nindent 4 }}
spec:
  group: tugboat.engineering
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                releasename:
                  type: string
            status:
              type: object
              properties:
                deployedat:
                  type: string
                revisions:
                  type: array
                  items:
                    type: object
                    properties:
                      revision:
                        type: integer
                      deployedat:
                        type: string
                      gvks:
                        type: object
                        properties:
                          additionalProperties: 
                            type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: releasename
          type: string
          jsonPath: .spec.releasename
        - name: releasenamespace
          type: string
          jsonPath: .metadata.namespace
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    kind: ReleaseHistory
    plural: releasehistories
    singular: releasehistory
    shortNames:
      - rhte
