/*
LICENSE
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ReleaseHistoryListerExpansion allows custom methods to be added to
// ReleaseHistoryLister.
type ReleaseHistoryListerExpansion interface{}

// ReleaseHistoryNamespaceListerExpansion allows custom methods to be added to
// ReleaseHistoryNamespaceLister.
type ReleaseHistoryNamespaceListerExpansion interface{}
