apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "tugboat.engineering-watcher-reader"
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
      