{{- if .Values.tugboatWatcher.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tugboat-watcher.serviceAccountName" . }}
  labels:
    {{- include "tugboat.labels" . | nindent 4 }}
  {{- with .Values.tugboatWatcher.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
