apiVersion: v1
kind: Service
metadata:
  name: {{ include "tugboat.fullname" . }}-watcher
  labels:
    {{- include "tugboat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tugboatWatcher.service.type }}
  ports:
    - port: {{ .Values.tugboatWatcher.service.externalPort }}
      targetPort: {{ .Values.tugboatWatcher.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "tugboat.selectorLabels" . | nindent 4 }}
