apiVersion: v1
kind: Service
metadata:
  name: {{ include "tugboat-controller.fullname" . }}
  labels:
    app: {{ template "tugboat-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- include "tugboat-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
    - port: 443
      targetPort: 3443
      protocol: TCP
      name: https
  selector:
    {{- include "tugboat-controller.selectorLabels" . | nindent 4 }}
