apiVersion: v1
kind: Service
metadata:
  name: {{ include "tugboat-notifier-slack.fullname" . }}
  labels:
    {{- include "tugboat-notifier-slack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: grpc
  selector:
    {{- include "tugboat-notifier-slack.selectorLabels" . | nindent 4 }}
