@startuml Create launch

box "client"
actor user
participant helm
end box
box "kubernetes"
participant kubeapi
participant etcd
end box
box "controller"
participant clientset
participant validatingwebhook
participant mutatingwebbook
participant reconciler
end box

user -> helm : helm upgrade -i
activate helm

helm -> kubeapi : create helm release
activate kubeapi

kubeapi -> validatingwebhook : notify release secret
activate validatingwebhook

validatingwebhook -> clientset : create releasehistory
activate clientset
clientset -> kubeapi : create releasehistory
activate kubeapi

kubeapi -> etcd : persist releasehistory
activate etcd
etcd -> kubeapi
deactivate etcd

kubeapi -> clientset

clientset -> validatingwebhook
deactivate clientset

kubeapi -> reconciler : update cache
activate reconciler
reconciler -> kubeapi
deactivate reconciler
deactivate kubeapi

validatingwebhook -> reconciler : ensure cache is updated
activate reconciler
reconciler -> validatingwebhook
deactivate reconciler

validatingwebhook -> kubeapi
deactivate validatingwebhook

kubeapi -> helm
deactivate kubeapi

loop each k8s resource
helm -> kubeapi : create k8s resources
activate kubeapi

kubeapi -> mutatingwebbook : notify k8s resource
activate mutatingwebbook
mutatingwebbook -> kubeapi : patch helm release id
deactivate mutatingwebbook

kubeapi -> etcd : persist k8s resource
activate etcd
etcd -> kubeapi
deactivate etcd

kubeapi -> helm
deactivate kubeapi
end

helm -> user
deactivate helm

@enduml